package com.smartparking.smart_parking_backend.model;

// Jakarta Persistence API (JPA) annotations for database mapping
import jakarta.persistence.*;
// Used to capture exact date and time of transactions
import java.time.LocalDateTime;

/**
 * Payout Model Class
 * 
 * Purpose: Represents a payment transfer (payout) made from the platform to a parking slot Owner.
 * It tracks who was paid, how much, and when.
 * 
 * Key Annotations:
 * - @Entity: Marks this class to be stored in the database.
 * - @Table: Specifies the database table name "payouts".
 */
@Entity
@Table(name = "payouts")
public class Payout {

    // Primary Key of the payouts table, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Many Payouts can be sent to one User (Owner).
     * FetchType.LAZY ensures the owner's details aren't loaded until specifically asked for, saving performance.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;

    // The monetary amount of the payout
    private double amount;

    // The status of the payout (e.g., "PAID")
    private String status; 

    // When the payout occurred
    private LocalDateTime transactionDate;

    // Default constructor needed by JPA
    public Payout() {
    }

    // Custom constructor to easily create a new payout object with initial values
    public Payout(User owner, double amount, String status) {
        this.owner = owner;
        this.amount = amount;
        this.status = status;
        this.transactionDate = LocalDateTime.now(); // Automatically record the current time
    }

    // ==========================================
    // MANUAL GETTERS AND SETTERS
    // These allow other parts of the Java application to access and modify these private fields securely.
    // ==========================================

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public User getOwner() { return owner; }
    public void setOwner(User owner) { this.owner = owner; }

    public double getAmount() { return amount; }
    public void setAmount(double amount) { this.amount = amount; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getTransactionDate() { return transactionDate; }
    public void setTransactionDate(LocalDateTime transactionDate) { this.transactionDate = transactionDate; }
}
