package com.smartparking.smart_parking_backend.model;

// Imports JPA annotations for handling database connections
import jakarta.persistence.*;

/**
 * Vehicle Model Class
 * 
 * Purpose: Represents a vehicle added by a user to their profile.
 * Users can store multiple vehicles and choose which one to park during the booking process.
 * 
 * Key Annotations:
 * - @Entity: Maps this class to a database table.
 * - @Table(name = "vehicles"): Specifically maps it to a table named "vehicles".
 */
@Entity
@Table(name = "vehicles")
public class Vehicle {

    // Unique ID for the vehicle, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // License plate or registration number
    private String vehicleNumber;
    
    // Model name (e.g., Honda Civic)
    private String vehicleModel;
    
    // @Enumerated(EnumType.STRING) stores the word (e.g., "CAR") in the database instead of a number
    // nullable = false means a vehicle MUST have a type assigned to it
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private VehicleType vehicleType;
    
    // Name of the person who owns the vehicle
    private String ownerName;

    /**
     * Many Vehicles can belong to one User.
     * @JoinColumn("user_id") creates a foreign key column in the database connecting the vehicle back to the user who added it.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    // Default constructor required by JPA
    public Vehicle() {
    }

    // ==========================================
    // MANUAL GETTERS AND SETTERS
    // Standard methods to read and write to the the private properties
    // ==========================================

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getVehicleNumber() { return vehicleNumber; }
    public void setVehicleNumber(String vehicleNumber) { this.vehicleNumber = vehicleNumber; }

    public String getVehicleModel() { return vehicleModel; }
    public void setVehicleModel(String vehicleModel) { this.vehicleModel = vehicleModel; }

    public VehicleType getVehicleType() { return vehicleType; }
    public void setVehicleType(VehicleType vehicleType) { this.vehicleType = vehicleType; }

    public String getOwnerName() { return ownerName; }
    public void setOwnerName(String ownerName) { this.ownerName = ownerName; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }
}
